"""Authoritative statistics for Experiment 19 -> results/exp19_stats.json.

Implements the pre-registered per-rung verdicts of FINDINGS_exp19.md:
for each (subject model, rung R1-R5) —
* topology-only failure-prediction AUC with item bootstrap CI
* confidence baseline, topology-beyond-confidence paired bootstrap
* mechanism scalars: r(topo_mean_persist, ctrl_attn_entropy) and
  topology-beyond-controls
* verdict: ALIVE / WEAK / DEAD / UNDERPOWERED
"""
from __future__ import annotations

import json

import numpy as np
import pandas as pd
from scipy.stats import pearsonr

from src.compute_stats_exp16 import (ALPHA, _bootstrap_auc, _bootstrap_delta,
                                     _fit_oof, _folds)

TOPO = ["topo_mean_persist", "topo_max_persist", "topo_frac_nontrivial"]
CTRL = ["ctrl_attn_distance", "ctrl_offdiag_mass", "ctrl_attn_entropy"]
CONF = ["confidence_margin"]
RUNGS = ("r1", "r2", "r3", "r4", "r5")
MODELS = ("0p5b", "1p5b")


def _rung_stats(df, rng):
    y = df["is_correct"].to_numpy(dtype=int)
    fail = 1 - y
    acc = float(y.mean())
    out = {"n_items": int(len(df)), "acc": acc}
    if not (0.15 <= acc <= 0.85):
        out["verdict"] = "UNDERPOWERED"
        return out
    folds = _folds(y)

    def oof(cols):
        o, _ = _fit_oof(df[cols].to_numpy(float), y, folds)
        return 1 - o  # predict failure

    topo_s, conf_s = oof(TOPO), oof(CONF)
    conf_topo_s, ctrl_s, ctrl_topo_s = (oof(CONF + TOPO), oof(CTRL),
                                        oof(CTRL + TOPO))

    topo_boot = _bootstrap_auc(fail, topo_s, rng)
    conf_boot = _bootstrap_auc(fail, conf_s, rng)
    add_conf = _bootstrap_delta(fail, conf_s, conf_topo_s, rng)
    add_ctrl = _bootstrap_delta(fail, ctrl_s, ctrl_topo_s, rng)
    r, r_p = pearsonr(df["topo_mean_persist"], df["ctrl_attn_entropy"])

    beats_chance = topo_boot["ci95"][0] > 0.5
    adds = add_conf["p_one_sided"] < ALPHA and add_conf["delta_auc"] > 0
    verdict = ("ALIVE" if beats_chance and adds
               else "WEAK" if beats_chance else "DEAD")
    out.update({
        "topology_only": topo_boot,
        "confidence_only": conf_boot,
        "topo_beyond_confidence": add_conf,
        "topo_beyond_controls": add_ctrl,
        "r_topo_entropy": {"r": float(r), "p": float(r_p)},
        "verdict": verdict,
    })
    return out


def compute_stats(out_path="results/exp19_stats.json"):
    rng = np.random.default_rng(0)
    stats = {"rungs": list(RUNGS), "alpha": ALPHA}
    for key in MODELS:
        path = f"results/exp19_features_{key}.parquet"
        try:
            df = pd.read_parquet(path)
        except FileNotFoundError:
            stats[key] = {"missing": True}
            continue
        stats[key] = {}
        for rung in RUNGS:
            sub = df[df["rung"] == rung].reset_index(drop=True)
            if len(sub) == 0:
                stats[key][rung] = {"n_items": 0, "verdict": "MISSING"}
                continue
            stats[key][rung] = _rung_stats(sub, rng)
    with open(out_path, "w") as f:
        json.dump(stats, f, indent=2)
    return stats


RESULTS_MARKER = "\n---\n\n## Results"


def write_findings(s, path="FINDINGS_exp19.md"):
    text = open(path).read()
    cut = text.find(RESULTS_MARKER)
    if cut != -1:
        text = text[:cut]
    blocks = [f"{RESULTS_MARKER} (generated by compute_stats_exp19 from "
              f"results/exp19_stats.json; do not edit)\n"]
    for key in MODELS:
        m = s.get(key, {})
        if m.get("missing"):
            continue
        rows = ["| rung | n | acc | topology AUC [CI95] | confidence | "
                "ΔAUC vs conf (p) | r(topo, entropy) | verdict |",
                "|---|---|---|---|---|---|---|---|"]
        for rung in RUNGS:
            r = m.get(rung, {})
            if r.get("verdict") in ("UNDERPOWERED", "MISSING"):
                rows.append(f"| {rung.upper()} | {r.get('n_items', 0)} | "
                            f"{r.get('acc', float('nan')):.3f} | — | — | — | — "
                            f"| {r.get('verdict')} |")
                continue
            t, c = r["topology_only"], r["confidence_only"]
            d = r["topo_beyond_confidence"]
            rows.append(
                f"| {rung.upper()} | {r['n_items']} | {r['acc']:.3f} | "
                f"{t['auc']:.3f} [{t['ci95'][0]:.3f}, {t['ci95'][1]:.3f}] | "
                f"{c['auc']:.3f} | {d['delta_auc']:.3f} "
                f"(p = {d['p_one_sided']:.4f}) | "
                f"{r['r_topo_entropy']['r']:.3f} | **{r['verdict']}** |")
        blocks.append(f"### Subject model {key}\n\n" + "\n".join(rows) + "\n")
    open(path, "w").write(text + "\n".join(blocks))
    print(f"updated {path}")


if __name__ == "__main__":
    s = compute_stats()
    write_findings(s)
    for key in MODELS:
        m = s.get(key, {})
        if m.get("missing"):
            print(f"{key}: missing")
            continue
        line = "  ".join(f"{r.upper()}:{m[r]['verdict']}" for r in RUNGS
                         if r in m)
        print(f"{key}: {line}")
