"""Generate WRITEUP.md from the two committed stats JSONs.

Consolidates the spike (results/real_stats.json) and Experiment 1
(results/exp1_stats.json) into one honest report. Every numeric value is read
from the JSON files; prose is fixed here. No number is hand-typed into the doc.
"""
from __future__ import annotations

import json


def _f(x, nd=2):
    try:
        return f"{float(x):.{nd}f}"
    except (TypeError, ValueError):
        return str(x)


def build(s: dict, e: dict) -> str:
    # --- spike numbers ---
    nontriv_pct = _f(s["c1_nontriv_frac"] * 100, 1)
    n_sig = s["c2_n_sig"]
    n_tested = s["c2_heads_tested"]
    sig_up = s["c2_sig_up"]
    sig_down = s["c2_sig_down"]
    layer_med = s["c3_sig_layer_median"]
    n_layers = s["layers"]
    kin_sig = s["kinship_sig"]
    ord_sig = s["ordering_sig"]
    overlap = s["family_overlap"]
    kin_len = s["kinship_len_diff"]
    pairs = s["pairs"]
    rows = s["rows"]

    # --- exp1 numbers ---
    ppl = e["wikitext_ppl_by_method"]
    ppl_order = sorted([m for m in ppl], key=lambda m: ppl[m])
    ppl_table = "\n".join(f"| {m} | {_f(ppl[m], 1)} |" for m in ppl_order)
    wil = e["wikitext_dmt_vs_baseline_loss"]
    wil_rows = []
    for b in ["magnitude", "window", "random"]:
        if b in wil:
            r = wil[b]
            md = r.get("median_diff")
            d = "DMT worse" if (md is not None and md > 0) else ("DMT better" if md is not None else "n/a")
            wil_rows.append(f"| dmt vs {b} | {_f(md, 3)} | {d} | {r.get('p')} |")
    wil_table = "\n".join(wil_rows)
    dmt_spars = _f(e["dmt_mean_sparsity"], 3)
    exp1_verdict = e["verdict"]
    n_wt = e["wikitext_n_examples"]

    return f"""# Topology of Attention — Consolidated Writeup

**One-line result:** the topology of a transformer's attention graph is **diagnostic**
of reasoning (it robustly tracks multi-hop structure) but **not prescriptive** for
pruning (discrete-Morse critical cells are not the right edges to keep). This matches
fallback direction #1 in the original proposal: keep topology as an interpretability
diagnostic, drop the sparsification angle.

All numbers in this document are generated by `src/write_writeup.py` from
`results/real_stats.json` (spike) and `results/exp1_stats.json` (Experiment 1). No value
is hand-typed.

---

## 1. Setup (shared)

- **Model(s):** Qwen2.5-0.5B(-Instruct), {n_layers} layers x {s["heads"]} heads, eager
  attention, float32. Experiment 1 also uses the base Qwen2.5-0.5B for perplexity.
- **Topology pipeline:** per (layer, head) attention matrix -> max-symmetrize -> top-k
  sparsify -> flag (clique) complex -> persistent homology (H1) or discrete Morse matching.
- **Reasoning probe data:** controlled minimal pairs differing only in hop-count
  (1-hop vs 2-hop) over identical context; kinship and spatial-ordering families.

---

## 2. Result A — Topology tracks reasoning (spike): GREEN

Question: does attention flag-complex H1 (cycles) carry non-trivial structure that
discriminates reasoning hop-count? Dataset: {pairs} matched pairs, {rows} head-observations.

| Pre-registered criterion | Result |
|---|---|
| Non-triviality (H1 present) | {nontriv_pct}% of head-observations carry a persistent cycle |
| Discrimination (2-hop vs 1-hop, paired Wilcoxon, BH-corrected) | {n_sig} / {n_tested} heads significant |
| Plausible localization | significant-head layer median {layer_med} / {n_layers} |

**Robustness (against a sequence-length artifact):**
- Effect is two-sided: {sig_up} heads increase H1 persistence for 2-hop, {sig_down} decrease it
  (a length artifact would be one-sided).
- The kinship family is exactly length-matched (mean token diff {_f(kin_len, 3)}) yet still
  yields {kin_sig} significant heads.
- Cross-family replication: kinship {kin_sig} and ordering {ord_sig} significant heads, with
  {overlap} heads significant in **both** families independently.

**Verdict:** {s["verdict"]}

Top discriminating heads (effect size d, BH-adjusted p):
{chr(10).join("- " + h for h in s["top_heads"])}

---

## 3. Result B — Topology does NOT improve pruning (Experiment 1): NULL

Question: at equal per-head edge budget, does pruning attention by discrete-Morse
critical cells preserve quality better than magnitude / sliding-window / random pruning?
DMT sets each head's budget k; baselines keep exactly k. Masking verified lossless on
all-keep. WikiText-2 perplexity on {n_wt} windows (base model).

### WikiText-2 mean perplexity by method (lower is better)

| method | mean PPL |
|---|---|
{ppl_table}

### Paired Wilcoxon on per-example loss: DMT vs each baseline

`median_diff` = median(DMT loss - baseline loss); positive = DMT worse.

| comparison | median_diff | direction | p |
|---|---|---|---|
{wil_table}

- DMT natural sparsity (fraction of candidate edges kept): {dmt_spars}.
- Kinship axis was uninformative (accuracy identical across methods, including unpruned).

**Verdict:** {exp1_verdict}

DMT critical cells are close to the *worst* edges to keep for language-modeling quality —
significantly worse than magnitude pruning at the same budget.

---

## 4. Synthesis

The two results are coherent, not contradictory. Attention topology **locates** where
reasoning structure lives (Result A) but the discrete-Morse critical set is **not** the
quality-preserving subgraph (Result B). The contribution, if any, is a *topological
diagnostic* for mechanistic interpretability — predicting which heads carry multi-hop
reasoning structure — rather than a sparse-attention method.

## 5. Honest caveats

- Single small model (0.5B); Experiment 1 was a small, memory-safe CPU run.
- Mean perplexity = mean(exp(loss)) is outlier-dominated; the paired per-example loss test
  is the more reliable comparison (and it agrees: DMT loses to magnitude/window).
- The kinship reasoning metric in Experiment 1 was uninformative and needs redesign.
- "Tracks reasoning" was shown on *attempted* reasoning (attention over the prompt), not
  gated on the model answering correctly.

## 6. What this opens up (next)

The live thread is the proposal's mechanistic-correspondence claim: do the
H1-discriminating heads (Result A localized them to mid/late layers) coincide with
*independently known* interpretability circuits (induction / IOI) in a model where those
circuits are documented (e.g. GPT-2 small)? That is cheap, model-light, and would turn
"topology is diagnostic" into "topology predicts known circuits."

---

*Provenance: spike verdict and Experiment 1 verdict are machine-checked fields in the
respective JSON files; regenerate this document with `uv run python -m src.write_writeup`.*
"""


def main(spike="results/real_stats.json", exp1="results/exp1_stats.json",
         out="WRITEUP.md"):
    s = json.load(open(spike))
    e = json.load(open(exp1))
    open(out, "w").write(build(s, e))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
