"""Generate FINDINGS_exp4.md mechanically from results/exp4_stats.json.

Every number is read from the JSON; prose is fixed here. No value is hand-typed.
"""
from __future__ import annotations

import json


def _f(x, nd=3):
    try:
        return f"{float(x):.{nd}f}"
    except (TypeError, ValueError):
        return str(x)


def build(s: dict) -> str:
    controls = ", ".join(s["controls"])
    models = ", ".join(s["models"])
    circuits = ", ".join(s["circuits"])

    header = ("| model | circuit | n_heads | baseline_r2 | full_r2 | delta_r2 |"
              " f_pvalue | partial_rho | verdict |")
    sep = "|---|---|---|---|---|---|---|---|---|"
    rows = []
    for c in s["cells"]:
        rows.append(
            f"| {c['model']} | {c['circuit']} | {c['n_heads']} | "
            f"{_f(c['baseline_r2'])} | {_f(c['full_r2'])} | {_f(c['delta_r2'])} | "
            f"{_f(c['f_pvalue'], 5)} | {_f(c['partial_spearman_rho'])} | "
            f"{c['cell_verdict']} |"
        )
    table = "\n".join([header, sep] + rows)

    return f"""# Experiment 4 Findings: Does the residual-information result generalize?

**Date:** 2026-05-31
**Overall verdict:** {s["overall_verdict"]}
**GREEN cells:** {s["n_green"]} of {s["n_cells"]}.

Every number here is generated by `src/write_findings_exp4.py` from
`results/exp4_stats.json` (produced by `src/compute_stats_exp4.py`). No value is
hand-typed — a guard adopted after earlier fabrication incidents in this project.

## Question
Experiment 3 found H1 persistence adds predictive power for the **induction** score
beyond first-order attention statistics in **GPT-2 small**. Does that residual
(non-redundant) signal generalize across more circuits and a second model? This is
a 2 models x 3 circuits = 6-cell grid of the same residual-information test.

- Models: {models}.
- Circuits: {circuits}.
- Controls (first-order scalars): {controls}.
- Feature tested for residual signal: {s["feature"]}.

## Pre-registered rule (fixed before running)
Per cell: **GREEN** iff delta-R^2 >= {_f(s["delta_r2_floor"], 2)} AND nested-model
F-test p < {_f(s["alpha"], 2)} (H1 adds meaningfully more variance and the term is
significant); **RED** otherwise (H1 redundant with first-order statistics for that
model+circuit).

Overall: **STRONG-GENERALIZE** iff >=5/6 GREEN; **PARTIAL-GENERALIZE** iff 2-4
GREEN; **DOES-NOT-GENERALIZE** iff <=1 GREEN.

## Grid
{table}

## Reading
The overall verdict and every cell verdict above are machine-checked against the
pre-registered rule and reported as-is, whatever the outcome. The (gpt2, induction)
cell is also a **replication check** of Experiment 3 (it should reproduce
delta-R^2 ~ 0.074); compare its row above against `results/exp3_stats.json`.

- A GREEN cell means H1 persistence carries information about that circuit's score
  that the first-order scalars (mean distance, off-diagonal mass, entropy) do not —
  topology is non-redundant for that model+circuit.
- A RED cell means H1 persistence is redundant with the first-order statistics for
  predicting that circuit's score.
- The overall verdict states how broadly the Exp 3 non-redundancy result holds: a
  STRONG result means it is a general property; PARTIAL means it depends on the
  circuit and/or model (see which cells are GREEN); DOES-NOT-GENERALIZE means Exp 3
  was likely induction-in-GPT2 specific.

## Caveats
- Two small models (gpt2, distilgpt2), CPU, modest batch (n_seqs<=8, seq_len<=25).
- Only one topological descriptor (scalar H1 total persistence) is tested.
- Three circuits, all detected on repeated-random sequences; this is not the full
  space of attention circuits.

## Reproduce
```bash
uv run python -m src.run_exp4              # results/exp4.parquet
uv run python -m src.compute_stats_exp4    # results/exp4_stats.json (source of truth)
uv run python -m src.write_findings_exp4   # this file
```
"""


def main(stats_path="results/exp4_stats.json", out_path="FINDINGS_exp4.md"):
    with open(stats_path) as f:
        s = json.load(f)
    with open(out_path, "w") as f:
        f.write(build(s))
    print(f"wrote {out_path} from {stats_path}")


if __name__ == "__main__":
    main()
