"""Generate WRITEUP.md from the three committed stats JSONs.

Consolidates the spike (results/real_stats.json), Experiment 1
(results/exp1_stats.json), and Experiment 2 (results/exp2_stats.json) into one
honest report. Every numeric value is read from the JSON files; prose is fixed
here. No number is hand-typed into the document.
"""
from __future__ import annotations

import json


def _f(x, nd=2):
    try:
        return f"{float(x):.{nd}f}"
    except (TypeError, ValueError):
        return str(x)


def build(s: dict, e: dict, x: dict) -> str:
    # --- spike numbers ---
    nontriv_pct = _f(s["c1_nontriv_frac"] * 100, 1)
    n_sig = s["c2_n_sig"]
    n_tested = s["c2_heads_tested"]
    sig_up = s["c2_sig_up"]
    sig_down = s["c2_sig_down"]
    layer_med = s["c3_sig_layer_median"]
    n_layers = s["layers"]
    kin_sig = s["kinship_sig"]
    ord_sig = s["ordering_sig"]
    overlap = s["family_overlap"]
    kin_len = s["kinship_len_diff"]
    pairs = s["pairs"]
    rows = s["rows"]

    # --- exp1 numbers ---
    ppl = e["wikitext_ppl_by_method"]
    ppl_order = sorted([m for m in ppl], key=lambda m: ppl[m])
    ppl_table = "\n".join(f"| {m} | {_f(ppl[m], 1)} |" for m in ppl_order)
    wil = e["wikitext_dmt_vs_baseline_loss"]
    wil_rows = []
    for b in ["magnitude", "window", "random"]:
        if b in wil:
            r = wil[b]
            md = r.get("median_diff")
            d = "DMT worse" if (md is not None and md > 0) else ("DMT better" if md is not None else "n/a")
            wil_rows.append(f"| dmt vs {b} | {_f(md, 3)} | {d} | {r.get('p')} |")
    wil_table = "\n".join(wil_rows)
    dmt_spars = _f(e["dmt_mean_sparsity"], 3)
    exp1_verdict = e["verdict"]
    n_wt = e["wikitext_n_examples"]

    # --- exp2 numbers ---
    x_rho = _f(x["spearman_rho"], 3)
    x_p = _f(x["spearman_p"], 5)
    x_mw_p = _f(x["mannwhitney_p"], 5)
    x_top_h1 = _f(x["top_mean_h1"], 3)
    x_rest_h1 = _f(x["rest_mean_h1"], 3)
    x_drho = _f(x["baseline_distance_rho"], 3)
    x_dp = _f(x["baseline_distance_p"], 5)
    x_notdom = x["topology_not_dominated_by_distance"]
    x_verdict = x["verdict"]
    x_heads = x["n_heads"]

    return f"""# Topology of Attention — Consolidated Writeup

**One-line result:** a transformer's attention-graph topology carries a *real,
reproducible* signal about reasoning (Spike, GREEN), but that signal is **not
prescriptive** for pruning (Experiment 1, NULL) and **not mechanistically specific** —
it does not localize a known circuit better than a trivial distance heuristic
(Experiment 2, RED). Net: topology correlates with reasoning structure, but we have no
evidence it captures anything a cheap first-order statistic does not.

All numbers in this document are generated by `src/write_writeup.py` from
`results/real_stats.json` (spike), `results/exp1_stats.json` (Exp 1), and
`results/exp2_stats.json` (Exp 2). No value is hand-typed.

---

## 1. Setup (shared)

- **Models:** Qwen2.5-0.5B(-Instruct), {n_layers} layers x {s["heads"]} heads (Spike, Exp 1);
  GPT-2 small, 12 x 12 = {x_heads} heads (Exp 2). Eager attention, float32, CPU/MPS.
- **Topology pipeline:** per (layer, head) attention matrix -> max-symmetrize -> top-k
  sparsify -> flag (clique) complex -> persistent homology (H1) or discrete Morse matching.
- **Probes:** controlled 1-hop/2-hop minimal pairs (Spike); WikiText-2 perplexity +
  budget-matched pruning baselines (Exp 1); repeated-random induction detector (Exp 2).

---

## 2. Result A — Topology tracks reasoning (Spike): GREEN

Does attention flag-complex H1 discriminate reasoning hop-count? {pairs} matched pairs,
{rows} head-observations.

| Pre-registered criterion | Result |
|---|---|
| Non-triviality (H1 present) | {nontriv_pct}% of head-observations carry a persistent cycle |
| Discrimination (2-hop vs 1-hop, paired Wilcoxon, BH-corrected) | {n_sig} / {n_tested} heads significant |
| Plausible localization | significant-head layer median {layer_med} / {n_layers} |

Robustness: effect is two-sided ({sig_up} heads up, {sig_down} down — not a one-sided
length artifact); the exactly length-matched kinship family (token diff {_f(kin_len, 3)})
still yields {kin_sig} significant heads; cross-family replication kinship {kin_sig} /
ordering {ord_sig} with {overlap} heads significant in both.

**Verdict:** {s["verdict"]}

Top discriminating heads:
{chr(10).join("- " + h for h in s["top_heads"])}

---

## 3. Result B — Topology does NOT improve pruning (Exp 1): NULL

At equal per-head edge budget, does pruning by discrete-Morse critical cells beat
magnitude / window / random? DMT sets the budget; baselines match it. WikiText-2 PPL on
{n_wt} windows (base model).

| method | mean PPL |
|---|---|
{ppl_table}

Paired Wilcoxon on per-example loss (`median_diff` = median(DMT - baseline); positive = DMT worse):

| comparison | median_diff | direction | p |
|---|---|---|---|
{wil_table}

DMT natural sparsity {dmt_spars}. **Verdict:** {exp1_verdict}

---

## 4. Result C — Topology does NOT match induction circuits (Exp 2): RED

Do topologically distinctive heads coincide with induction heads (detected independently)?
GPT-2 small, {x_heads} heads.

- Discrimination: Spearman(induction, H1 persistence) rho = {x_rho}, p = {x_p}.
- Separation: top-10 induction heads vs rest, Mann-Whitney p = {x_mw_p}
  (mean H1 {x_top_h1} vs {x_rest_h1}).
- Beats trivial baseline? Spearman(induction, attention distance) rho = {x_drho},
  p = {x_dp}. Topology not dominated by distance: {x_notdom}.

The cheap attention-distance scalar predicts induction *better* than H1 persistence does.
**Verdict:** {x_verdict}

---

## 5. Synthesis

The three results are coherent. Topology **locates** where reasoning structure lives
(A), but the discrete-Morse critical set is **not** the quality-preserving subgraph (B),
and topological distinctiveness is **not** a better circuit-locator than a one-line
attention statistic (C). The defensible contribution is narrow: H1 persistence is a real
but **first-order-redundant** correlate of reasoning structure. The strong proposal
claims (topological pruning; topology predicts circuits) are not supported at this scale.

## 6. Honest caveats

- Exp 1 and Exp 2 were small, memory-safe CPU runs; directions are clear but magnitudes
  are not nailed down. The Spike is the largest and most robust run.
- Mean PPL = mean(exp(loss)) is outlier-dominated; the paired per-example loss test agrees
  with the NULL verdict regardless.
- "Tracks reasoning" (Spike) was measured on *attempted* reasoning (attention over the
  prompt), not gated on correct answers.
- Single model per experiment; one circuit (induction) tested in Exp 2.

## 7. Follow-up research directions

Four candidates, roughly ordered by how directly they build on what we have:

1. **Residual-information test (is topology redundant?).** The sharpest open question from
   Exp 2: does H1 persistence add *anything* beyond first-order attention statistics (mean
   distance, entropy, off-diagonal mass)? Regress the reasoning/circuit signal on those
   scalars and test whether topology has residual predictive power. If it never does, the
   honest paper is "topological features of attention are redundant with simple statistics."
   Cheap; reuses all existing data. **Highest information-per-compute.**

2. **Failure prediction (Spike's payoff / proposal Exp 3).** Train a probe on per-example
   topological features to predict reasoning errors on held-out items. This is the
   application the Spike's positive result actually supports, and it is the only proposal
   claim still untested. Moderate cost; strongest evidence base.

3. **Beyond-H1 / better descriptors.** We used only the crudest summary (scalar total
   persistence). Try H0 (attention clusters), persistence images/landscapes as feature
   vectors, and honest graph-statistic competitors (spectral gap, modularity, motifs). If a
   $10 graph statistic matches topology, that reframes the project.

4. **Sheaves over the residual stream (proposal fallback #2).** The flag complex discards
   *what* flows along edges. A cellular sheaf with stalks from OV-circuit subspaces keeps
   the linear-algebraic content; sheaf cohomology may capture structure pure graph topology
   cannot. Highest-risk, highest-ceiling; most new machinery.

## 8. Provenance

Spike / Exp 1 / Exp 2 verdicts are machine-checked fields in the respective JSON files.
Regenerate this document with `uv run python -m src.write_writeup`.
"""


def main(spike="results/real_stats.json", exp1="results/exp1_stats.json",
         exp2="results/exp2_stats.json", out="WRITEUP.md"):
    s = json.load(open(spike))
    e = json.load(open(exp1))
    x = json.load(open(exp2))
    open(out, "w").write(build(s, e, x))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
