"""Generate FINDINGS_exp2.md mechanically from results/exp2_stats.json.

Every number is read from the JSON; prose is fixed here. No value is hand-typed.
"""
from __future__ import annotations

import json


def _f(x, nd=3):
    try:
        return f"{float(x):.{nd}f}"
    except (TypeError, ValueError):
        return str(x)


def build(s: dict) -> str:
    heads = "\n".join("- " + h for h in s["top_induction_heads"])
    return f"""# Experiment 2 Findings: Topology vs Induction Heads

**Date:** 2026-05-30
**Verdict:** {s["verdict"]}

Every number here is generated by `src/write_findings_exp2.py` from
`results/exp2_stats.json` (produced by `src/compute_stats_exp2.py`). No value is
hand-typed — a guard adopted after earlier fabrication incidents in this project.

## Question
Do attention heads with distinctive H1 topology coincide with induction heads, a circuit
detected independently of any topology? Model: GPT-2 small, {s["n_heads"]} heads.

## Pre-registered tests
- **Discrimination** — Spearman(induction score, H1 persistence): rho = {_f(s["spearman_rho"])},
  p = {_f(s["spearman_p"], 5)}.
- **Separation** — top-{s["top_k"]} induction heads vs the rest, H1 persistence
  (Mann-Whitney, greater): U = {_f(s["mannwhitney_u"], 1)}, p = {_f(s["mannwhitney_p"], 5)}.
  Mean H1 persistence: top induction heads {_f(s["top_mean_h1"])} vs rest {_f(s["rest_mean_h1"])}.
- **Beats trivial baseline** — Spearman(induction, attention distance): rho =
  {_f(s["baseline_distance_rho"])}, p = {_f(s["baseline_distance_p"], 5)}. Topology not
  dominated by distance: {s["topology_not_dominated_by_distance"]}.

## Top induction heads (by induction score)
{heads}

## Reading
The verdict field above is machine-checked against the pre-registered rule (GREEN: topology
corresponds to induction beyond the distance baseline; YELLOW: correlates but the trivial
baseline does as well; RED: no correspondence). Whatever the outcome, it is reported as-is.

## Plot
- results/exp2_scatter.png — induction score vs H1 persistence, top induction heads marked.

## Caveats
- Single model (GPT-2 small), CPU, modest batch.
- Induction is one circuit; correspondence (or its absence) here does not generalize to all
  circuits (IOI etc. untested).

## Reproduce
```bash
uv run python -m src.run_exp2              # results/exp2.parquet
uv run python -m src.compute_stats_exp2    # results/exp2_stats.json (source of truth)
uv run python -m src.write_findings_exp2   # this file
uv run python -m src.analyze_exp2          # results/exp2_scatter.png
```
"""


def main(stats_path="results/exp2_stats.json", out_path="FINDINGS_exp2.md"):
    with open(stats_path) as f:
        s = json.load(f)
    with open(out_path, "w") as f:
        f.write(build(s))
    print(f"wrote {out_path} from {stats_path}")


if __name__ == "__main__":
    main()
