"""Generate FINDINGS_exp1.md mechanically from results/exp1_stats.json.

Every number is read from the JSON and formatted here — no value is ever typed by
hand into the findings. (This project had repeated fabrication incidents; this
script makes hand-typing impossible.)
"""
from __future__ import annotations

import json


def _fmt(x, nd=3):
    try:
        return f"{float(x):.{nd}f}"
    except (TypeError, ValueError):
        return str(x)


def build(stats: dict) -> str:
    ppl = stats["wikitext_ppl_by_method"]
    order = ["unpruned", "dmt", "magnitude", "window", "random"]
    ppl_rows = sorted(
        [m for m in order if m in ppl], key=lambda m: ppl[m]
    )
    ppl_table = "\n".join(f"| {m} | {_fmt(ppl[m])} |" for m in ppl_rows)

    wil = stats["wikitext_dmt_vs_baseline_loss"]
    wil_rows = []
    for b in ["magnitude", "window", "random"]:
        if b in wil:
            r = wil[b]
            md = r.get("median_diff")
            # median_diff = dmt_loss - baseline_loss; >0 means DMT worse
            direction = "DMT worse" if (md is not None and md > 0) else (
                "DMT better" if md is not None else "n/a")
            wil_rows.append(
                f"| dmt vs {b} | {_fmt(md)} | {direction} | {r.get('p')} |"
            )
    wil_table = "\n".join(wil_rows)

    kin = stats["kinship_accuracy_by_method"]
    kin_line = ", ".join(f"{m}={_fmt(kin[m],2)}" for m in order if m in kin)

    verdict = stats["verdict"]
    spars = stats["dmt_mean_sparsity"]
    n_wt = stats.get("wikitext_n_examples")
    n_kin = stats.get("kinship_n_examples")

    return f"""# Experiment 1 Findings: DMT Attention Pruning

**Date:** 2026-05-30
**Verdict:** {verdict}

Every number in this file is generated by `src/write_findings_exp1.py` directly from
`results/exp1_stats.json` (itself produced by `src/compute_stats_exp1.py`). No value is
hand-typed. This guard exists because earlier in the project result numbers were fabricated
more than once; the findings are now machine-generated from disk.

## Setup
- Base model Qwen/Qwen2.5-0.5B (WikiText-2 perplexity); instruct model
  Qwen/Qwen2.5-0.5B-Instruct (kinship).
- Methods: unpruned, dmt, magnitude, random, window. DMT sets each head's edge budget *k*;
  baselines keep exactly *k* per head (equal sparsity, per-head).
- Masking: additive bias (0 keep / -inf drop) before softmax via the Qwen2
  eager_attention_forward monkeypatch; verified lossless on all-keep.
- Memory-safe CPU run: {n_wt} WikiText windows + {n_kin} kinship items.

## WikiText-2 mean perplexity by method (lower is better)

| method | mean PPL |
|---|---|
{ppl_table}

## Paired Wilcoxon on per-example WikiText loss: DMT vs each baseline

`median_diff` = median(DMT loss − baseline loss); positive means DMT is **worse**.

| comparison | median_diff | direction | p-value |
|---|---|---|---|
{wil_table}

## Kinship accuracy by method
{kin_line}

## DMT sparsity
- Mean DMT kept-edge fraction (WikiText): {_fmt(spars, 4)}

## Honest reading
The pre-registered claim was that DMT pruning beats magnitude (and random and window) at
equal per-head budget. Read the tables above against that bar; the `verdict` field states
the machine-checked outcome. Where DMT loses or ties, that is reported as-is — a real
negative is a valid result and matches the proposal's anticipated fallback (topology as a
diagnostic rather than a pruning method). The kinship axis is uninformative on this run
(accuracy is identical across methods, including unpruned), so it constrains nothing yet.

## Plots
- results/exp1_ppl_by_method.png
- results/exp1_dmt_vs_magnitude.png
- results/exp1_dmt_sparsity.png

## Caveats / next steps
- Small run (CPU, memory-safe after MPS crashes); scale up before drawing strong conclusions.
- Mean PPL = mean(exp(loss)) is outlier-dominated; report median per-token loss too.
- Fix the kinship metric (full masked generation or correctness-gated items).
- Try higher sparsity and later-layer-only pruning.

## Reproduce
```bash
EXP1_N_WIKI=12 EXP1_KIN_PER_FAM=6 EXP1_MAXTOK=32 EXP1_THREADS=2 \\
  uv run python -u -m src.run_exp1_gentle results/exp1.parquet
uv run python -m src.compute_stats_exp1     # results/exp1_stats.json
uv run python -m src.write_findings_exp1    # this file
uv run python -m src.analyze_exp1           # plots
```
"""


def main(stats_path="results/exp1_stats.json", out_path="FINDINGS_exp1.md"):
    with open(stats_path) as f:
        stats = json.load(f)
    md = build(stats)
    with open(out_path, "w") as f:
        f.write(md)
    print(f"wrote {out_path} from {stats_path}")


if __name__ == "__main__":
    main()
