"""Generate FINDINGS_exp3.md mechanically from results/exp3_stats.json.

Every number is read from the JSON; prose is fixed here. No value is hand-typed.
"""
from __future__ import annotations

import json


def _f(x, nd=3):
    try:
        return f"{float(x):.{nd}f}"
    except (TypeError, ValueError):
        return str(x)


def build(s: dict) -> str:
    controls = ", ".join(s["controls"])
    return f"""# Experiment 3 Findings: Residual-Information Test (is H1 topology redundant?)

**Date:** 2026-05-30
**Verdict:** {s["verdict"]}

Every number here is generated by `src/write_findings_exp3.py` from
`results/exp3_stats.json` (produced by `src/compute_stats_exp3.py`). No value is
hand-typed — a guard adopted after earlier fabrication incidents in this project.

## Question
Does H1 persistence add ANY predictive power for induction score beyond first-order
attention statistics? Controls (first-order scalars): {controls}.
Model: GPT-2 small, {s["n_heads"]} heads.

## Pre-registered rule
GREEN iff delta-R^2 >= {_f(s["delta_r2_floor"], 2)} AND nested-model F-test
p < {_f(s["alpha"], 2)} (H1 explains meaningfully more induction-score variance
and the added term is significant). RED otherwise (H1 redundant with first-order
statistics). Fixed before computing on real data.

## Results
- **Baseline OLS** (induction ~ {controls}): R^2 = {_f(s["baseline_r2"])}
  (adj R^2 = {_f(s["baseline_adj_r2"])}).
- **Full OLS** (baseline + h1_persistence): R^2 = {_f(s["full_r2"])}
  (adj R^2 = {_f(s["full_adj_r2"])}).
- **delta-R^2** (variance added by H1) = {_f(s["delta_r2"])}.
- **Nested-model F-test** for adding H1: F = {_f(s["f_stat"])},
  p = {_f(s["f_pvalue"], 5)}.
- **H1 coefficient** in the full model = {_f(s["h1_coef"])}
  (t-test p = {_f(s["h1_coef_p"], 5)}).
- **Partial Spearman**(h1, induction | controls): rho =
  {_f(s["partial_spearman_rho"])}, p = {_f(s["partial_spearman_p"], 5)}.
- For reference, **raw Spearman**(h1, induction): rho =
  {_f(s["raw_spearman_rho"])}, p = {_f(s["raw_spearman_p"], 5)}.

## Reading
The verdict field above is machine-checked against the pre-registered rule. If RED,
the honest interpretation is: topological H1 persistence is redundant with simple
first-order attention statistics for predicting the induction circuit — it carries
no information about induction that mean distance, off-diagonal mass, and entropy do
not already carry. This is reported as-is, whatever the outcome.

## Relation to the consolidated writeup
This sharpens Experiment 2's RED. Exp 2 showed mean attention distance predicts
induction better than H1 alone; Exp 3 controls for three first-order scalars at
once and asks whether H1 adds residual signal. `WRITEUP.md` (generated by
`src/write_writeup.py` from the spike/exp1/exp2 JSONs) was NOT regenerated to
include Exp 3, to avoid hand-editing numbers into it; the authoritative Exp 3
result lives in `results/exp3_stats.json` and this file.

## Caveats
- Single model (GPT-2 small), CPU, modest batch.
- One circuit (induction). Redundancy here does not prove redundancy for every
  reasoning signal; the spike measured a different (reasoning hop-count) target.
- Only one topological descriptor (scalar H1 total persistence) is tested; richer
  descriptors (persistence images, H0, sheaves) are separate follow-ups.

## Reproduce
```bash
uv run python -m src.run_exp3              # results/exp3.parquet
uv run python -m src.compute_stats_exp3    # results/exp3_stats.json (source of truth)
uv run python -m src.write_findings_exp3   # this file
```
"""


def main(stats_path="results/exp3_stats.json", out_path="FINDINGS_exp3.md"):
    with open(stats_path) as f:
        s = json.load(f)
    with open(out_path, "w") as f:
        f.write(build(s))
    print(f"wrote {out_path} from {stats_path}")


if __name__ == "__main__":
    main()
